### ISSUE TITLE
Use Nuget or local references for DNN assemblies

### ISSUE THREAD

**Issue by jbrinkman** [davidjrh/dnn.bot#3]
The DotNetNuke.dll and DotNetNuke.Web.dll are both available as Nuget packages which will make this code more portable to other machines.

Any references which are not available as nuget packages should be referenced from a local folder in the project rather than relying on a specific configuration of your hard-drive.  This ensures that others can download and compile the code without having to figure out how you have organized directory structures on your machine.

**Comment by davidjrh** [comment]
Fixed on https://github.com/davidjrh/dnn.bot/commit/907419836c9fd56b18594efeb44ae0c62c2e9066
